# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - azure-pipelines
 paths:
    include:
    - '*.tf'
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
#  path: PutMyCodeHere   # will checkout at $(Pipeline.Workspace)/PutMyCodeHere



- task: iacScan@1
  inputs:
    fname: '$(System.DefaultWorkingDirectory)'
    High: '1'
    Medium: '1'
    Low: '1'
    Operator: 'or'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
