# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - azure-pipelines
 paths:
    include:
    - '*.tf'
    exclude:
    - '.git'
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
#  path: PutMyCodeHere   # will checkout at $(Pipeline.Workspace)/PutMyCodeHere

- task: iacScan@1
  inputs:
    Path: 'scan'
    prismaCloudService: 'PrismaService'
    High: '1'
    Medium: '6'
    Low: '1'
    Operator: 'or'

- task: twistcli-scan@1

  inputs:
    scanType: 'images'
    twistlockService: 'twistlockservice'
    vulnerabilityThreshold: 'high'
    onlyFixed: false
    gracePeriod: '0'
    complianceThreshold: 'high'
    artifact: 'alpine:latest'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
