# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - azure-pipelines
 paths:
    include:
    - '*.tf'
    exclude:
    - '.git'
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
#  path: PutMyCodeHere   # will checkout at $(Pipeline.Workspace)/PutMyCodeHere
- task: iacScan@1
  inputs:
    Path: 'scan'
    prismaCloudService: 'PrismaService'
    High: '0'
    Medium: '3'
    Low: '0'
    Operator: 'or'
- task: iacScan@1
  inputs:
    Path: 'scan'
    prismaCloudService: 'PrismaIacScan'
    High: '1'
    Medium: '0'
    Low: '0'
    Operator: 'or'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
