version: 0.2

# In this example, we're using environment variables
# to store the username & password of our Twistlock CI user account
# and the URL to our console

# TL_USER:  The Twistlock user with the CI User role
# TL_PASS:  The password for this user account
# TL_CONSOLE_URL:  The base URL for the console -- http://console.<my_company>.com:8083 -- without a trailing /
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image..$IMAGE_TAG  
      - docker build -t $IMAGE_REPO_NAME:IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - curl -k -u $TL_USER:$TL_PASS --output ./twistcli http://54.193.112.152:8081/api/v1/util/twistcli
      - ls -la
      - chmod +x ./twistcli
      - ls -la
      - echo Scanning with twistcli $TL_PASS $TL_USER
      - ./twistcli images scan --details -address $TL_CONSOLE_URL -u $TL_USER -p $TL_PASS $IMAGE_REPO_NAME:IMAGE_TAG 
#artifacts:
  #files:
    #- target/my-app-1.0-SNAPSHOT.jar
    #- appspec.yml
